# Generated by Django 5.2.12 on 2026-06-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_build_builditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, help_text='Example: 32GB, 2TB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pcie_generation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='power_draw',
            field=models.PositiveIntegerField(blank=True, help_text='Power consumption in Watts', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_psu',
            field=models.PositiveIntegerField(blank=True, help_text='Recommended PSU Wattage', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='socket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supported_cpu_sockets',
            field=models.CharField(blank=True, help_text='Comma separated. Example: AM4,AM5,LGA1700', max_length=200, null=True),
        ),
    ]
