# Generated by Django 5.2.12 on 2026-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_capacity_product_memory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='form_factor',
            field=models.CharField(blank=True, help_text='ATX, Micro-ATX, Mini-ITX', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supported_form_factors',
            field=models.CharField(blank=True, help_text='Example: ATX,Micro-ATX,Mini-ITX', max_length=100, null=True),
        ),
    ]
