# Generated by Django 5.2.12 on 2026-06-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_form_factor_product_supported_form_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cooler_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu_length',
            field=models.IntegerField(blank=True, help_text='Length in mm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='m2_slots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_cooler_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_gpu_length',
            field=models.IntegerField(blank=True, help_text='Maximum supported GPU length', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sata_ports',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_interface',
            field=models.CharField(blank=True, choices=[('M.2', 'M.2'), ('SATA', 'SATA')], max_length=20, null=True),
        ),
    ]
