# Generated by Django 5.2.12 on 2026-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cooler_height_product_gpu_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='build_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='efficiency_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fps_1080p',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fps_1440p',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fps_4k',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gaming_score',
            field=models.PositiveIntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='product',
            name='learning_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productivity_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tier',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Budget', 'Budget'), ('Mid Range', 'Mid Range'), ('High End', 'High End'), ('Flagship', 'Flagship')], max_length=20),
        ),
    ]
