# Generated by Django 5.2.12 on 2026-07-22 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_benchmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='created_at',
        ),
        migrations.AddField(
            model_name='build',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL),
        ),
    ]
