# Generated by Django 5.2.12 on 2026-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_build_created_at_build_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='build',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
