# Generated by Django 5.2.12 on 2026-07-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_build_description_build_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_type',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('streaming', 'Streaming'), ('workstation', 'Workstation'), ('editing', 'Editing'), ('office', 'Office'), ('ai', 'AI / Machine Learning'), ('mini_itx', 'Mini ITX'), ('server', 'Server / NAS'), ('custom', 'Custom')], default='gaming', max_length=20),
        ),
    ]
